print("Fer:hola Simba")
print("Simba: Miau...")
print("Fer: Quieres comer croquetas?")
print("Simba: si Miau")
print("Fer: Ok Simba, son de atun")
print("Simba: Si me gusta el atun miau")
print("Fer: Bueno ya te servi, buen provecho Simba")
print("Simba:Gracias Miau...")
print("Fer: bye")
print("Simba: Adios")